---
# Install aurora agent 
- name: Copy the aurora agent zip
  ansible.builtin.copy:
    src: aurora-agent.zip
    dest: 'c:\ludus'

- name: Unzip agent to aurora folder
  community.windows.win_unzip:
    src: 'c:\ludus\aurora-agent.zip'
    dest: 'c:\aurora'
    delete_archive: true
    creates: 'c:\aurora'

- name: Copy the aurora agent licence
  ansible.builtin.copy:
    src: aurora-agent.lic
    dest: 'c:\aurora'

# not find a better way for the dashboard :)
# get an error with --dashboard option
- name: Install aurora
  ansible.windows.win_command:
    cmd: 'C:\aurora\aurora-agent-64.exe --install'

- name: Copy Dashboard
  ansible.windows.win_copy:
    src: 'C:\aurora\tools'
    dest: 'C:\Program Files\Aurora-Agent'
    remote_src: true
  when: ludus_aurora_dashboard

- name: Add dashboard Run RegKey
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\windows\CurrentVersion\Run'
    name: aurora-dashboard
    data: 'C:\Program Files\Aurora-Agent\tools\aurora-dashboard.exe'
  when: ludus_aurora_dashboard

- name: clean folder
  ansible.windows.win_file:
    path: 'C:\aurora'
    state: absent

