---
- name: Clone caldera
  ansible.builtin.git:
    repo: 'https://github.com/mitre/caldera.git'
    dest: /opt/caldera
    recursive: true
    track_submodules: true
    force: true

- name: Copy custom config
  ansible.builtin.template:
    src: local.yml.j2
    dest: /opt/caldera/conf/local.yml

- name: Copy custom magma .env
  ansible.builtin.template:
    src: magma.env.j2
    dest: /opt/caldera/plugins/magma/.env

- name: Install caldera python requirements file
  ansible.builtin.pip:
    requirements: "{{ item }}"
    virtualenv: /opt/caldera/venv
  loop:
    - /opt/caldera/requirements.txt
    - /opt/caldera/requirements-dev.txt
    - /opt/caldera/plugins/human/requirements.txt
    - /opt/caldera/plugins/emu/requirements.txt

- name: Install caldera python fix AsyncSSH error
  ansible.builtin.pip:
    name: asyncssh
    state: latest
    virtualenv: /opt/caldera/venv

- name: Caldera - Sancat gocat plugins
  ansible.builtin.shell:
    cmd: "{{ item }}" 
    chdir: /opt/caldera/plugins/sandcat/gocat
  loop:
    - go mod tidy
    - go mod download

- name: Caldera - sancat update agent
  ansible.builtin.command:
    cmd: ./update-agents.sh
    chdir: /opt/caldera/plugins/sandcat

- name: Clone atomic read team
  ansible.builtin.git:
    repo: 'https://github.com/redcanaryco/atomic-red-team.git'
    dest: /opt/caldera/plugins/atomic/data/atomic-red-team
    depth: 1
    force: true

# need to enter a password 
#- name: Caldera - emu - download_payloads
#  ansible.builtin.shell:
#    cmd: ./download_payloads.sh
#    chdir: /opt/caldera/plugins/emu

- name: Caldera - Magma plugins
  ansible.builtin.command:
    cmd: "{{ item }}" 
    chdir: /opt/caldera/plugins/magma
  loop:
    - npm install
    - npm audit fix --force
    - npm run build

