---

- name: Download go tar
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ludus_caldera_go_version}}.linux-amd64.tar.gz
    dest: /tmp/go{{ludus_caldera_go_version}}.linux-amd64.tar.gz
    mode: '0666'

- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
 
- name: Extract and move new go folder to /usr/local
  ansible.builtin.unarchive:
    src: /tmp/go{{ludus_caldera_go_version}}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
 
- name: Delete downloaded tar file
  ansible.builtin.file:
    path: /tmp/go{{ludus_caldera_go_version}}.linux-amd64.tar.gz
    state: absent

- name: Add go binary path to /root/.bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'PATH=$PATH:/usr/local/go/bin'
    create: true
    state: present

- name: Add go binary path to /home/localuser/.bashrc
  ansible.builtin.lineinfile:
    path: /home/localuser/.bashrc
    line: 'PATH=$PATH:/usr/local/go/bin'
    create: true
    state: present

- name: Add go binary path to /etc/environment
  ansible.builtin.replace:
    path: /etc/environment
    regexp: 'PATH="(.*)"'
    replace: 'PATH="\g<1>:/usr/local/go/bin"'

- name: Break sudoers path security :)
  ansible.builtin.replace:
    path: /etc/sudoers
    regexp: '^Defaults(.+)secure_path=(.*)$'
    replace: '#Defaults\g<1>secure_path=\g<2>'
