---
- name: Install requirements
  ansible.builtin.apt:
    name: 
      - git
      - curl 
      - python3
      - python3-pip
      - python3-virtualenv
      - mingw-w64
      - zlib1g
      - unzip
      - upx
      - golang-go
      - nodejs 
      - npm
    state: present
    update_cache: yes
    install_recommends: yes

- name: Install Caldera
  ansible.builtin.include_tasks:
    file: caldera.yml

