---
# https://caldera.readthedocs.io/en/latest/Installing-Caldera.html
# https://github.com/mitre/caldera/blob/master/Dockerfile
# https://github.com/nodesource/distributions?tab=readme-ov-file#ubuntu-versions

- name: Check that /opt/caldera exists
  stat:
    path: /opt/caldera
  register: stat_result   

- name: Install Caldera on Ubuntu 22.xx
  ansible.builtin.include_tasks:
    file: install_ubuntu_2204.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22' and not stat_result.stat.exists

- name: Install Caldera on Ubuntu 24.xx
  ansible.builtin.include_tasks:
    file: install_ubuntu_2404.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '24' and not stat_result.stat.exists

